### ISSUE TITLE
Launch webuiセルでのエラー

### ISSUE THREAD

**Issue by PseudoCydonia** [ddPn08/rvc-webui-colab#1]
実行環境: Google Colab Pro（Tesla T4, メモリ標準）
Launch webuiセルで、以下のエラーが発生して停止するようになってしまいました。

--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/rvc-webui/webui.py", line 26, in <module>
    webui()
  File "/content/rvc-webui/webui.py", line 16, in webui
    app = ui.create_ui()
  File "/content/rvc-webui/modules/ui.py", line 128, in create_ui
    with block:
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1262, in get_config_file
    "output": list(block.output_api_info()),  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/gradio_client/serializing.py", line 45, in output_api_info
    return (api_info["serialized_output"][0], api_info["serialized_output"][1])
KeyError: 'serialized_output'
--------------------------------------------------------------------------------------

考えうる修正箇所につき、ご教示いただければ幸いです。
どうぞよろしくお願いいたします。

**Comment by PseudoCydonia** [comment]
一過性のものだったようです（Gradioの更新による？）
お騒がせいたしました。
